# ══════════════════════════════════════════════════════════════════════════════
# streamlit_catboost_app.py
# Run with:  streamlit run streamlit_catboost_app.py
# Requires:  CatBoost_package.pkl  (generated by CatBoost_Package.py)
# ══════════════════════════════════════════════════════════════════════════════

import streamlit as st
import pandas as pd
import numpy as np
import joblib
import warnings
warnings.filterwarnings("ignore")

# ── Page config ────────────────────────────────────────────────────────────────
st.set_page_config(
    page_title="CatBoost Adsorption Predictor",
    page_icon="🌿",
    layout="wide",
    initial_sidebar_state="expanded",
)

# ══════════════════════════════════════════════════════════════════════════════
# Williams-plot / leverage (applicability-domain) helpers — INLINE.
# NOTE: identical design-matrix logic (_one_hot / _build_design_matrix) also
# lives in CatBoost_Package.py, which is what fit XtX_inv / h_star in the
# first place. If you ever change the math here, copy the change there too —
# otherwise a new sample gets scored against a different design matrix than
# the one the training leverages were computed on.
# ══════════════════════════════════════════════════════════════════════════════

def _one_hot(df, col, categories):
    cat = pd.Categorical(df[col].astype(str), categories=categories)
    return pd.get_dummies(cat, prefix=col)

def _build_design_matrix(df, numerical_cols, categorical_cols, cat_categories,
                          scaler_mean, scaler_scale):
    num = df[numerical_cols].astype(float).values
    num_scaled = (num - scaler_mean) / scaler_scale
    dummy_blocks = [
        _one_hot(df, c, cat_categories[c]).values.astype(float)
        for c in categorical_cols
    ]
    intercept = np.ones((len(df), 1))
    return np.hstack([intercept, num_scaled] + dummy_blocks)

def compute_leverage(row_df, leverage_artifacts):
    """row_df: 1-row DataFrame with the raw input feature values."""
    x = _build_design_matrix(
        row_df,
        leverage_artifacts['numerical_cols'],
        leverage_artifacts['categorical_cols'],
        leverage_artifacts['cat_categories'],
        leverage_artifacts['scaler_mean'],
        leverage_artifacts['scaler_scale'],
    )
    return float(x @ leverage_artifacts['XtX_inv'] @ x.T)

def classify_confidence(h, h_star, medium_multiplier=3.0):
    """
    High   : h <= h*                        (inside the training domain)
    Medium : h*  < h <= medium_multiplier*h* (borderline extrapolation)
    Low    : h  > medium_multiplier*h*       (well outside training domain)
    """
    if h <= h_star:
        return "High"
    elif h <= medium_multiplier * h_star:
        return "Medium"
    else:
        return "Low"

# ══════════════════════════════════════════════════════════════════════════════

# ── Styling ────────────────────────────────────────────────────────────────────
st.markdown("""
<style>
[data-testid="stAppViewContainer"] {background: #f0f4f8;}
[data-testid="stSidebar"]          {background: #1a2e3b; color: white;}
[data-testid="stSidebar"] *        {color: white !important;}

.card {
    background: white;
    border-radius: 12px;
    padding: 20px 24px 14px 24px;
    margin-bottom: 18px;
    box-shadow: 0 2px 8px rgba(0,0,0,0.08);
}
.card-title {
    font-size: 15px; font-weight: 700; letter-spacing: .5px;
    margin-bottom: 10px; padding-bottom: 6px; border-bottom: 2px solid;
    display: flex; align-items: center; gap: 7px;
}
.cat1-title {border-color: #2b9c8f; color: #2b9c8f;}
.cat2-title {border-color: #7c4daa; color: #7c4daa;}
.cat3-title {border-color: #d9641e; color: #d9641e;}

.page-title    {font-size: 28px; font-weight: 800; color: #0d1f2d; margin-bottom: 4px;}
.page-subtitle {font-size: 15px; color: #2c3e50; font-weight: 500; margin-bottom: 0px;}

.ratio-box   {background: #eef6f5; border: 1.5px solid #2b9c8f; border-radius: 8px;
               padding: 8px 12px; margin-top: 4px; margin-bottom: 10px;}
.ratio-label {font-size: 12px; color: #555; font-weight: 600; margin-bottom: 2px;}
.ratio-value {font-size: 22px; font-weight: 800; color: #1a7a6e;}

.result-box   {background: linear-gradient(135deg, #1a2e3b 0%, #2b5870 100%);
                border-radius: 14px; padding: 28px 24px; text-align: center;
                color: white; margin-top: 16px; box-shadow: 0 4px 18px rgba(26,46,59,0.25);}
.result-label {font-size: 16px; opacity: .75; margin-bottom: 6px;}
.result-value {font-size: 52px; font-weight: 800; letter-spacing: -1px;}
.result-unit  {font-size: 20px; opacity: .65;}
.result-sub   {font-size: 13px; opacity: .6; margin-top: 8px;}

.metric-card  {background: white; border-radius: 10px; padding: 14px 18px;
                box-shadow: 0 1px 6px rgba(0,0,0,0.07); text-align: center;}
.metric-label {font-size: 12px; color: #666; font-weight: 600; margin-bottom: 4px;}
.metric-val   {font-size: 22px; font-weight: 800; color: #1a2e3b;}
.metric-std   {font-size: 12px; color: #888;}

div[data-testid="stButton"] > button {
    background: linear-gradient(135deg, #2b9c8f, #1a7a6e) !important;
    color: white !important; font-size: 17px !important; font-weight: 700 !important;
    border-radius: 10px !important; padding: 14px 40px !important; border: none !important;
    width: 100%; box-shadow: 0 3px 10px rgba(43,156,143,.35) !important;
}
div[data-testid="stButton"] > button:hover {filter: brightness(1.1);}

[data-testid="stNumberInput"] label, [data-testid="stSelectbox"] label,
div[data-testid="stWidgetLabel"] p, div[data-testid="stWidgetLabel"] label {
    color: #111111 !important; font-weight: 600 !important;
}
</style>
""", unsafe_allow_html=True)

# ══════════════════════════════════════════════════════════════════════════════
# LOAD PACKAGE
# ══════════════════════════════════════════════════════════════════════════════
PKG_PATH = "G:/My Drive/NEU/research/research/Kim project 2/NEW_REJECTED/Codes/13 GUI/CatBoost_package.pkl"

@st.cache_resource(show_spinner="Loading CatBoost model…")
def load_package(path):
    return joblib.load(path)

try:
    pkg = load_package(PKG_PATH)
except FileNotFoundError:
    st.error(f"**Package not found:** `{PKG_PATH}` — run `CatBoost_Package.py` first.")
    st.stop()

model              = pkg['model']
feature_names      = pkg['feature_names']
categorical_cols   = pkg['categorical_cols']
numerical_cols     = pkg['numerical_cols']
biomass_values     = pkg['biomass_values']
pollutant_values   = pkg['pollutant_values']
cv_results         = pkg['cv_results']
train_metrics_f    = pkg['train_metrics_final']
test_metrics_f     = pkg['test_metrics_final']
oof_preds          = pkg['oof_preds']
oof_actuals        = pkg['oof_actuals']
y_train_arr        = pkg['y_train']
train_preds_final  = pkg['train_preds_final']
y_test_arr         = pkg['y_test']
test_preds_final   = pkg['test_preds_final']
feat_importances   = pkg['feat_importances']

leverage_artifacts = pkg['leverage']          # <-- NEW
h_star             = leverage_artifacts['h_star']   # <-- NEW
X_train_raw        = pkg['X_train']           # <-- NEW: real training rows, for Random Sample

# ── Feature groupings (adjust slice indices to match your actual feature list) ─
GROUPS = {
    "🔥 Pyrolysis Conditions":    feature_names[0:4],
    "🧬 Biochar Characteristics": feature_names[4:15],
    "⚗️  Adsorption Conditions":  feature_names[15:],
}
GROUP_CLASSES = {
    "🔥 Pyrolysis Conditions":    "cat1",
    "🧬 Biochar Characteristics": "cat2",
    "⚗️  Adsorption Conditions":  "cat3",
}

C_COL  = 'C (%)'
H_COL  = 'H (%)'
O_COL  = 'O (%)'
HC_COL = 'H/C'
OC_COL = 'O/C'
AUTO_COMPUTED = {HC_COL, OC_COL}

CONF_COLORS = {"High": "#2b9c8f", "Medium": "#e0a800", "Low": "#c0392b"}  # <-- NEW

# ══════════════════════════════════════════════════════════════════════════════
# SIDEBAR
# ══════════════════════════════════════════════════════════════════════════════
with st.sidebar:
    st.markdown("## 🌿 CatBoost Predictor")
    st.markdown("---")
    st.markdown("**Model:** CatBoostRegressor")
    st.markdown(f"**Features:** {len(feature_names)}")
    st.markdown(f"**Categoricals:** {', '.join(categorical_cols)}")
    st.markdown("---")

    st.markdown("### 📊 Model Performance")
    r2_v  = cv_results['R2']['val_mean']
    r2_vs = cv_results['R2']['val_std']
    r2_t  = test_metrics_f['R2']
    rmse_v  = cv_results['RMSE']['val_mean']
    rmse_vs = cv_results['RMSE']['val_std']
    rmse_t  = test_metrics_f['RMSE']
    st.markdown(f"**R² Validation:** {r2_v:.4f} ± {r2_vs:.4f}")
    st.markdown(f"**R² Test:**        {r2_t:.4f}")
    st.markdown(f"**RMSE Validation:** {rmse_v:.4f} ± {rmse_vs:.4f}")
    st.markdown(f"**RMSE Test:**       {rmse_t:.4f}")
    st.markdown("---")

    st.markdown("### ℹ️ How to use")
    st.markdown(
        "1. Fill in feature values below\n"
        "2. H/C and O/C update automatically\n"
        "3. Press **Predict** to get Qe\n"
        "4. Use **Random Sample** to explore"
    )
    st.markdown("---")

    if st.button("🎲 Fill Random Sample", key="rand_btn", use_container_width=True):
        # Draw one REAL row from the training set (not independently randomized
        # per-feature) so the sample reflects an actual, plausible combination.
        sample_row = X_train_raw.sample(n=1).iloc[0]
        for f in feature_names:
            if f in AUTO_COMPUTED:
                continue  # H/C and O/C recompute live from C/H/O
            val = sample_row[f]
            if f in categorical_cols:
                st.session_state[f'inp_{f}'] = str(val)
            else:
                st.session_state[f'inp_{f}'] = round(float(val), 4)
        st.rerun()

# ══════════════════════════════════════════════════════════════════════════════
# PAGE HEADER
# ══════════════════════════════════════════════════════════════════════════════
st.markdown(
    '<p class="page-title">🌿 Biochar Adsorption Capacity Predictor</p>'
    '<p class="page-subtitle">Predict equilibrium adsorption capacity '
    '<b>Qe (mg/g)</b> using a CatBoost model with native categorical support '
    'and Optuna-tuned hyperparameters.</p>',
    unsafe_allow_html=True
)
st.markdown("---")

# ══════════════════════════════════════════════════════════════════════════════
# INPUT FORM
# ══════════════════════════════════════════════════════════════════════════════
input_vals = {}
form_cols  = st.columns(len(GROUPS))

for col_obj, (group_name, group_features) in zip(form_cols, GROUPS.items()):
    cls = GROUP_CLASSES[group_name]
    with col_obj:
        st.markdown(
            f'<div class="card">'
            f'<div class="card-title {cls}-title">{group_name}</div>',
            unsafe_allow_html=True,
        )

        for feat in group_features:

            if feat == 'Biomass':
                cur = st.session_state.get(f'inp_{feat}', biomass_values[0])
                idx = biomass_values.index(cur) if cur in biomass_values else 0
                val = st.selectbox("Biomass", biomass_values, index=idx,
                                   key=f'inp_{feat}',
                                   help="Feedstock type used to produce biochar")
                input_vals[feat] = val

            elif feat == 'Pollutant':
                cur = st.session_state.get(f'inp_{feat}', pollutant_values[0])
                idx = pollutant_values.index(cur) if cur in pollutant_values else 0
                val = st.selectbox("Pollutant", pollutant_values, index=idx,
                                   key=f'inp_{feat}',
                                   help="Target pollutant for adsorption")
                input_vals[feat] = val

            elif feat in AUTO_COMPUTED:
                c_now = float(st.session_state.get(f'inp_{C_COL}', 0.0) or 0.0)
                h_now = float(st.session_state.get(f'inp_{H_COL}', 0.0) or 0.0)
                o_now = float(st.session_state.get(f'inp_{O_COL}', 0.0) or 0.0)

                if feat == HC_COL:
                    live_val = round(h_now / c_now, 4) if c_now > 0 else 0.0
                else:
                    live_val = round(o_now / c_now, 4) if c_now > 0 else 0.0

                st.markdown(
                    f'<div class="ratio-box">'
                    f'<div class="ratio-label">{feat} &nbsp;(auto-calculated)</div>'
                    f'<div class="ratio-value">{live_val:.4f}</div>'
                    f'</div>',
                    unsafe_allow_html=True
                )
                input_vals[feat] = live_val

            else:
                val = st.number_input(
                    feat,
                    value=float(st.session_state.get(f'inp_{feat}', 0.0)),
                    format="%.4f",
                    key=f'inp_{feat}'
                )
                input_vals[feat] = val

        st.markdown('</div>', unsafe_allow_html=True)

# Sync ratios for prediction
c_val = float(input_vals.get(C_COL, 0.0) or 0.0)
h_val = float(input_vals.get(H_COL, 0.0) or 0.0)
o_val = float(input_vals.get(O_COL, 0.0) or 0.0)
input_vals[HC_COL] = round(h_val / c_val, 4) if c_val > 0 else 0.0
input_vals[OC_COL] = round(o_val / c_val, 4) if c_val > 0 else 0.0

# ══════════════════════════════════════════════════════════════════════════════
# PREDICT BUTTON
# ══════════════════════════════════════════════════════════════════════════════
st.markdown("")
_, btn_col, _ = st.columns([1, 2, 1])
with btn_col:
    predict_clicked = st.button("⚡ Predict Qe (mg/g)", key="predict_btn")

# ══════════════════════════════════════════════════════════════════════════════
# RESULT
# ══════════════════════════════════════════════════════════════════════════════
if predict_clicked:
    errors = []
    numeric_vals = [v for k, v in input_vals.items()
                    if k not in categorical_cols and isinstance(v, (int, float))]
    if any(v < 0 for v in numeric_vals):
        errors.append("All numeric inputs must be ≥ 0.")
    if c_val <= 0:
        errors.append("C (%) must be > 0 to compute H/C and O/C ratios.")

    if errors:
        for e in errors:
            st.error(f"❌ {e}")
    else:
        with st.spinner("Running CatBoost model…"):
            try:
                row = pd.DataFrame([input_vals])
                for col in categorical_cols:
                    row[col] = row[col].astype(str)
                row = row[feature_names]
                qe  = float(model.predict(row)[0])

                # ── NEW: Williams leverage / confidence ───────────────────────
                h = compute_leverage(row, leverage_artifacts)
                confidence = classify_confidence(h, h_star)
                conf_color = CONF_COLORS[confidence]
                # ───────────────────────────────────────────────────────────────

                _, res_col, _ = st.columns([1, 2, 1])
                with res_col:
                    st.markdown(
                        f"""
                        <div class="result-box">
                            <div class="result-label">Predicted Equilibrium Adsorption Capacity</div>
                            <div class="result-value">{qe:.2f}</div>
                            <div class="result-unit">mg / g</div>
                            <div class="result-sub">CatBoost · Optuna-tuned · 5-fold Nested CV</div>
                            <div style="margin-top:14px; padding-top:10px; border-top:1px solid rgba(255,255,255,0.25);">
                                <span style="font-size:13px; opacity:.75;">Reliability (Williams leverage)</span><br>
                                <span style="font-size:22px; font-weight:800; color:{conf_color};">{confidence} Confidence</span><br>
                                <span style="font-size:12px; opacity:.6;">h = {h:.4f} &nbsp;|&nbsp; h* = {h_star:.4f}</span>
                            </div>
                        </div>
                        """,
                        unsafe_allow_html=True,
                    )

            except Exception as ex:
                st.error(f"⚠️ Prediction failed: {ex}")
                st.exception(ex)

# ══════════════════════════════════════════════════════════════════════════════
# PERFORMANCE METRICS (Scatter Plot, Feature Importance, and Williams Plot tabs removed)
# ══════════════════════════════════════════════════════════════════════════════
st.markdown("---")
st.markdown("#### Nested CV + Held-out Test Metrics")

key_metrics = ['R2', 'AR2', 'EVS', 'RMSE', 'MAE', 'MAPE', 'SMAPE', 'RSR', 'CVRMSE', 'RAE']
rows = []
for mn in key_metrics:
    r = cv_results[mn]
    rows.append({
        'Metric'          : mn,
        'Train (mean)'    : f"{r['train_mean']:.4f}",
        'Train (± std)'   : f"± {r['train_std']:.4f}",
        'Val (mean)'      : f"{r['val_mean']:.4f}",
        'Val (± std)'     : f"± {r['val_std']:.4f}",
        'Test (held-out)' : f"{test_metrics_f[mn]:.4f}",
    })
st.dataframe(pd.DataFrame(rows).set_index('Metric'), use_container_width=True)

# Summary cards for key metrics
st.markdown("#### Key Metric Cards")
card_metrics = ['R2', 'RMSE', 'MAE', 'SMAPE']
cols = st.columns(len(card_metrics))
for col_obj, mn in zip(cols, card_metrics):
    r = cv_results[mn]
    with col_obj:
        st.markdown(
            f'<div class="metric-card">'
            f'<div class="metric-label">{mn}</div>'
            f'<div class="metric-val">{r["val_mean"]:.4f}</div>'
            f'<div class="metric-std">± {r["val_std"]:.4f} (val) &nbsp;|&nbsp; '
            f'{test_metrics_f[mn]:.4f} (test)</div>'
            f'</div>',
            unsafe_allow_html=True
        )

# ══════════════════════════════════════════════════════════════════════════════
# FOOTER
# ══════════════════════════════════════════════════════════════════════════════
st.markdown("---")
st.markdown(
    "<p style='text-align:center; color:#888; font-size:13px;'>"
    "CatBoostRegressor · Optuna HPO · 5-fold Nested CV · "
    "Zero Data Leakage · Train / Val / Test split</p>",
    unsafe_allow_html=True,
)